---
- name: Install Packages | apt
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - php7.0-fpm

- name: Install PHP 7.0 | apt
  apt:
    state: latest
    name: "{{ item }}"
  with_items: "{{ php_modules }}"
